### ISSUE TITLE
Error creating rule engine.

### ISSUE THREAD

**Issue by vitorrey** [protegeproject/swrlapi-drools-engine#2]
I compiled everything from source and all code passed the tests, but when I run a simple example where I create a SWRLRuleEngine, I get the following exception:

java.lang.NullPointerException
	at org.drools.rule.builder.PackageBuildContext.init(PackageBuildContext.java:105)
	at org.drools.rule.builder.RuleBuildContext.<init>(RuleBuildContext.java:78)
	at org.drools.compiler.PackageBuilder.addRule(PackageBuilder.java:3225)
	at org.drools.compiler.PackageBuilder.compileRules(PackageBuilder.java:1038)
	at org.drools.compiler.PackageBuilder.compileAllRules(PackageBuilder.java:946)
	at org.drools.compiler.PackageBuilder.addPackage(PackageBuilder.java:938)
	at org.drools.compiler.PackageBuilder.addPackageFromDrl(PackageBuilder.java:470)
	at org.drools.compiler.PackageBuilder.addKnowledgeResource(PackageBuilder.java:698)
	at org.drools.builder.impl.KnowledgeBuilderImpl.add(KnowledgeBuilderImpl.java:51)
	at org.drools.builder.impl.KnowledgeBuilderImpl.add(KnowledgeBuilderImpl.java:40)
	at org.swrlapi.drools.core.DroolsResourceHandler.defineDRLResource(DroolsResourceHandler.java:167)
	at org.swrlapi.drools.core.DroolsResourceHandler.defineDRLRule(DroolsResourceHandler.java:30)
	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.defineDRLRule(DroolsSWRLRuleEngine.java:241)
	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.resetRuleEngine(DroolsSWRLRuleEngine.java:145)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.reset(DefaultSWRLRuleEngine.java:94)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.importSWRLRulesAndOWLKnowledge(DefaultSWRLRuleEngine.java:58)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.<init>(DefaultSWRLRuleEngine.java:48)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:81)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:60)
	at org.swrlapi.core.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:236)
	at main.RuleManager.<init>(RuleManager.java:24)
	at main.Main.main(Main.java:24)
Exception in thread "main" org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: org.swrlapi.exceptions.TargetSWRLRuleEngineInternalException. Message: internal error generating Drools rule 
rule prp_eqp2_dp when EDPA($p1:p1id, $p2:p2id) DPAA($x:s, pid==$p2, $y:o) then DPAA dpaa=new DPAA($x, $p1, $y); inferrer.infer(dpaa); end
null
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:83)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:60)
	at org.swrlapi.core.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:236)
	at main.RuleManager.<init>(RuleManager.java:24)
	at main.Main.main(Main.java:24)
Caused by: org.swrlapi.exceptions.TargetSWRLRuleEngineInternalException: internal error generating Drools rule 
rule prp_eqp2_dp when EDPA($p1:p1id, $p2:p2id) DPAA($x:s, pid==$p2, $y:o) then DPAA dpaa=new DPAA($x, $p1, $y); inferrer.infer(dpaa); end
null
	at org.swrlapi.drools.core.DroolsResourceHandler.defineDRLRule(DroolsResourceHandler.java:33)
	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.defineDRLRule(DroolsSWRLRuleEngine.java:241)
	at org.swrlapi.drools.core.DroolsSWRLRuleEngine.resetRuleEngine(DroolsSWRLRuleEngine.java:145)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.reset(DefaultSWRLRuleEngine.java:94)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.importSWRLRulesAndOWLKnowledge(DefaultSWRLRuleEngine.java:58)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngine.<init>(DefaultSWRLRuleEngine.java:48)
	at org.swrlapi.core.impl.DefaultSWRLRuleEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleEngineFactory.java:81)
	... 4 more
Caused by: java.lang.NullPointerException
	at org.drools.rule.builder.PackageBuildContext.init(PackageBuildContext.java:105)
	at org.drools.rule.builder.RuleBuildContext.<init>(RuleBuildContext.java:78)
	at org.drools.compiler.PackageBuilder.addRule(PackageBuilder.java:3225)
	at org.drools.compiler.PackageBuilder.compileRules(PackageBuilder.java:1038)
	at org.drools.compiler.PackageBuilder.compileAllRules(PackageBuilder.java:946)
	at org.drools.compiler.PackageBuilder.addPackage(PackageBuilder.java:938)
	at org.drools.compiler.PackageBuilder.addPackageFromDrl(PackageBuilder.java:470)
	at org.drools.compiler.PackageBuilder.addKnowledgeResource(PackageBuilder.java:698)
	at org.drools.builder.impl.KnowledgeBuilderImpl.add(KnowledgeBuilderImpl.java:51)
	at org.drools.builder.impl.KnowledgeBuilderImpl.add(KnowledgeBuilderImpl.java:40)
	at org.swrlapi.drools.core.DroolsResourceHandler.defineDRLResource(DroolsResourceHandler.java:167)
	at org.swrlapi.drools.core.DroolsResourceHandler.defineDRLRule(DroolsResourceHandler.java:30)
	... 10 more

The java test is simply calling

this.engine = SWRLAPIFactory.createSWRLRuleEngine(ont,
				new DroolsSWRLRuleEngineCreator());

where ont is just the classic pizza.owl ontology.

**Comment by zippyrate** [comment]
This repository has not yet been publicly released. See the README here 

https://github.com/protegeproject/swrltab-plugin

An announcement will be made on the protege-dev mailing list:

http://protege.stanford.edu/support.php
