### ISSUE TITLE
java.lang.ClassNotFoundException: org.drools.runtime.rule.AgendaFilter

### ISSUE THREAD

**Issue by nmerkle** [protegeproject/swrlapi-drools-engine#4]
Hi all,

I want to use the SWRLAPI and build both SWRLAPI and SWRLAPI-DROOLS-ENGINE with maven.  I put the generated jars into my eclipse project. As I ran my Java Main class the following exception was thrown: 

`Exception in thread "main" org.swrlapi.exceptions.SWRLRuleEngineException: Error creating rule engine Drools. Exception: java.lang.NoClassDefFoundError. Message: org/drools/runtime/rule/AgendaFilter
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:73)
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:43)
	at org.swrlapi.factory.SWRLAPIFactory.createSWRLRuleEngine(SWRLAPIFactory.java:79)
	at de.ruleengine.nic.RuleHelper.<init>(RuleHelper.java:27)
	at de.ruleengine.nic.Test.main(Test.java:6)
Caused by: java.lang.NoClassDefFoundError: org/drools/runtime/rule/AgendaFilter
	at org.swrlapi.drools.core.DroolsSWRLRuleEngineCreator.create(DroolsSWRLRuleEngineCreator.java:27)
	at org.swrlapi.factory.DefaultSWRLRuleAndQueryEngineFactory.createSWRLRuleEngine(DefaultSWRLRuleAndQueryEngineFactory.java:61)
	... 4 more
Caused by: java.lang.ClassNotFoundException: org.drools.runtime.rule.AgendaFilter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 6 more
`
I am searching since a while and I did not find the reason for this exception. It seems there is a class (org.drools.runtime.rule.AgendaFilter) missing. As I checked the swrlapi-drools-engine.jar file it did not contain the appropriate package and class. Any idea, what is going wrong or what I can do?

Best,
N.

**Comment by martinjoconnor** [comment]
The SWRLAPI's dependencies are relatively complex. I would first verify that you can build on the command line using the instructions in the Maven-based [SWRLAPI Build Project](https://github.com/protegeproject/swrlapi-project). I would then import that project into Eclipse, which will ensure proper dependency management.

See: http://javapapers.com/java/import-maven-project-into-eclipse/
